[package]
name = "learn_opengl"
version = "0.1.0"
edition = "2021"

[lib]
name = "learn_opengl"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14"
glfw = "0.54"
